Feature/assignment 3
nikhil1-successive/backend-training pull request #3
Opened 2023-11-20 18:04 UTC by nikhil1-successive

2023-12-06 07:01 UTC, shahbaz-successive commented on src/utils/mockData.js
> +const nameData = ["Nikhil", "Somil", "Sanskr"]
As stated in question, create a module that means create a function that return a seeded data with logs as well such as 'Data seeding started', 'Data seeding in progress', 'Data seeding completed'

2023-12-06 07:14 UTC, shahbaz-successive commented on src/routes/userRoutes.js
> +router.get('/authorized', tokenVerificationMiddleware, (req, res) => {
Rename tokenVerificationMiddleware to authMiddleware

2023-12-06 10:19 UTC, nikhil1-successive commented on src/routes/userRoutes.js
> +router.get('/authorized', tokenVerificationMiddleware, (req, res) => {
done

2023-12-06 10:21 UTC, nikhil1-successive commented on src/routes/userRoutes.js
> +router.get('/console', customMiddleware, (req, res) => {
done

2023-12-06 11:28 UTC, shahbaz-successive commented on src/middleware/tokenVerificationMiddleware.js
> +  const token = req.headers['authorization']
Define secretKey to decode token as a constant

2023-12-06 17:48 UTC, nikhil1-successive commented on src/utils/mockData.js
> +const nameData = ["Nikhil", "Somil", "Sanskr"]
done

2023-12-06 17:48 UTC, nikhil1-successive commented on src/routes/userRoutes.js
> +import tokenVerificationMiddleware from '../middleware/tokenVerificationMiddleware.js'
done

2023-12-06 17:48 UTC, nikhil1-successive commented on src/middleware/tokenVerificationMiddleware.js
> +  const token = req.headers['authorization']
done

2023-12-07 07:17 UTC, shahbaz-successive requested changes
Feedback

2023-12-07 08:30 UTC, nikhil1-successive commented on src/routes/userRoutes.js
> +  const { name } = req.body;
done

2023-12-07 08:30 UTC, nikhil1-successive commented on src/middleware/authMiddleware.js
> +const secretKey = 'Nikhil'
done

2023-12-07 11:21 UTC, merged