Feature/assignment 7
nikhil1-successive/backend-training pull request #7
Opened 2023-12-07 11:17 UTC by nikhil1-successive

2023-12-27 07:21 UTC, shahbaz-successive commented on src/app.ts
> +class MyApp {
If class is used then file name should be starting capital letter

2023-12-27 07:27 UTC, shahbaz-successive commented on src/lib/math.ts
> +class MathOperations {
File name should start with Capital as you're using class function

2023-12-27 07:30 UTC, shahbaz-successive commented on src/middleware/locationMiddleware.ts
> +interface GeoLocationMiddlewareOptions {
interface declaration should start with letter I

2023-12-27 07:30 UTC, shahbaz-successive commented on src/utils/mockData.ts
> +export interface User {
interface declaration should start with letter I

2023-12-27 07:32 UTC, shahbaz-successive requested changes
Please rename all file names where using class function to start with capital letter
Interface declaration should start with capital letter I throughout project

2023-12-27 08:20 UTC, nikhil1-successive commented on src/app.ts
> +class MyApp {
done

2023-12-27 08:20 UTC, nikhil1-successive commented on src/lib/math.ts
> +class MathOperations {
done

2023-12-27 08:20 UTC, nikhil1-successive commented on src/middleware/locationMiddleware.ts
> +interface GeoLocationMiddlewareOptions {
done

2023-12-27 08:20 UTC, nikhil1-successive commented on src/utils/mockData.ts
> +export interface User {
done

2023-12-28 04:43 UTC, shahbaz-successive commented on src/middleware/AuthMiddleware.ts
> +    jwt.verify(token as string, this.secretKey, (err, decodeUser) => {
Provide type to err and decodeUser

2023-12-28 04:45 UTC, shahbaz-successive commented on src/routes/userRoutes.ts
> +const errorHandler = new ErrorHandlerMiddleware();
Add type to all these variables

2023-12-28 04:45 UTC, shahbaz-successive commented on src/routes/userRoutes.ts
>      const token = jwt.sign(
Add type to token

2023-12-28 04:45 UTC, shahbaz-successive commented on src/routes/userRoutes.ts
> +  const dataSeeder = new DataSeeder();
Add type

2023-12-28 04:46 UTC, shahbaz-successive commented on src/utils/RegistrationValidationSchema.ts
> +const registrationValidator = new RegistrationValidator();
Add type

2023-12-28 04:47 UTC, shahbaz-successive commented on src/utils/ValidationRules.ts
> +const requestValidator = new RequestValidator(validationRules);
Add type

2023-12-28 04:47 UTC, shahbaz-successive requested changes
Feedback done

2023-12-30 10:05 UTC, shahbaz-successive approved these changes
👍

2023-12-30 10:05 UTC, merged